# Generated by Django 5.1.6 on 2025-03-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kise_user_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
